import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavigationBar from "@/Components/NavigationBar/NavigationBar";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>TalentIn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />

        {/* GOOGLE FONTS */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className={styles.main}>
        <NavigationBar />
        <section className={styles.hero_section}>
          <h1>Book a Photographer</h1>
          <p>
            Connecting Artists to Opportunities – A platform where artists
            showcase talent, network, and find gigs or work across the globe
          </p>

          <button className={`${styles.cta_button} bubble_eff`}>
            Get Started
            <Image
              src="/icons/arrow_right.svg"
              height={18}
              width={18}
              alt="right arrow"
            />
          </button>
        </section>
      </div>
    </>
  );
}
