import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavigationBar from "@/Components/NavigationBar/NavigationBar";
import HeroSection from "@/Components/HeroSection/HeroSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>TalentIn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />

        {/* GOOGLE FONTS */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className={styles.Main}>
        <NavigationBar />
        <HeroSection />
      </div>
    </>
  );
}
